language: python
python:
    - 3.5
    - 3.6
    - 3.6-dev
    - 3.7-dev
install:
  - python3 -m pip install -U git+git://github.com/python/mypy.git
  - pip install -e .
script: python setup.py test

matrix:
  allow_failures:
    python: "3.7-dev"
